name: bruning
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  freezed_annotation: ^2.4.1
  sqflite: ^2.3.0
  path: ^1.8.3
  cached_network_image: ^3.3.0
  debounce_throttle: ^2.0.0
  flutter_riverpod: ^2.6.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.6

flutter:
  uses-material-design: true
